---
- name: Set up Spark master
  hosts: spark_master
  remote_user: centos

  pre_tasks:
    - meta: refresh_inventory
  
  roles: 
    - spark-master

- name: Set up Cassandra nodes
  hosts: cassandra_all
  remote_user: centos

  pre_tasks:
    - meta: refresh_inventory

  roles:
    - cassandra
    - spark-slave

    