---

- name: 'TCP IPv4'
  become: yes
  sysctl: name='{{item.name}}' value='{{item.value}}' reload=no
  with_items:
    - { name: 'net.ipv4.tcp_tw_reuse',        value: '1' }
    - { name: 'net.ipv4.tcp_tw_recycle',      value: '1' }
    - { name: 'net.ipv4.tcp_rmem',            value: '4096 87380 16777216' }
    - { name: 'net.ipv4.tcp_wmem',            value: '4096 65536 16777216' }
    - { name: 'net.ipv4.tcp_max_syn_backlog', value: '4096' }
    - { name: 'net.core.rmem_max',            value: '16777216' }
    - { name: 'net.core.wmem_max',            value: '16777216' }
    - { name: 'net.core.netdev_max_backlog',  value: '2500' }

- name: 'Restart TCP'
  become: yes
  command: /etc/init.d/network restart
  
